/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.76.0
  Forc version: 0.51.1
  Fuel-Core version: 0.22.1
*/

export type { SingleAssetTokenAbi } from './SingleAssetTokenAbi';

export { SingleAssetTokenAbi__factory } from './factories/SingleAssetTokenAbi__factory';
